# Nixpacks configuration for Railway
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
